### ISSUE TITLE
Good job! Do you have plan to support motor2.0?

### ISSUE THREAD

**Issue by LanserShi** [ilex/aiomongodel#1]
aiomongodel is what i'm looking for to deploy ODM in tornado, but it's a bit old to support session in MongoDB 4. Would you update this project and support motor2.0 in future?

**Comment by ilex** [comment]
Yes, I'm going to move requirement to motor 2.0

**Comment by LanserShi** [comment]
Do you consider add delete rules to RefField as ReferenceField in pymodm?
