### ISSUE TITLE
triying use it

### ISSUE THREAD

**Issue by Barceloch** [ilex/aiomongodel#9]
hi friend, I want try use aiomongodel but the documentations is little, can you help me with some suggest to
migrate this https://pastebin.com/77ZnmDqG for use it?

my biggest doubt is with the use of session, what would be the
alternative to the db_session decorator of pony.orm

**Comment by ilex** [comment]
Maybe this https://aiomongodel.readthedocs.io/en/latest/getting-started.html#transaction is what you want?

**Comment by Barceloch** [comment]
> Maybe this https://aiomongodel.readthedocs.io/en/latest/getting-started.html#transaction is what you want?

yes I was looking that..., there are some field for file, for example in an "Image(Document)" to upload?...

**Comment by ilex** [comment]
Do you mean storing blobs in gridfs? If so then the answer is no. There is no such type of document (as it requires using a different  [API](https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_gridfs.html).)  You can also try [AnyField](https://aiomongodel.readthedocs.io/en/latest/api/index.html#aiomongodel.fields.AnyField)

**Comment by Barceloch** [comment]
I tryin this https://pastebin.com/nf8KVZiw

but get this error:
`ERROR:  Transaction numbers are only allowed on a replica set member or mongos, full error: {'ok': 0.0, 'errmsg': 'Transaction numbers are only allowed on a replica set member or mongos', 'code': 20, 'codeName': 'IllegalOperation'}`

I try achieve the same that in pony.orm with db_session like this:
https://pastebin.com/n1fTSzb1

in other hand, can I do some like this?
```
u = await User(username="user" ) #<------without save yet
u.set_password("abcd")
u.save(db, session=session)  #<-------------save after some action
```

**Comment by ilex** [comment]
The error seems to be not relative to the library but to the configuration of your mongodb. Probably you should read how transactions work in mongodb and how to set up replica sets.

**Comment by ilex** [comment]
`await` should be used only with coroutines, not with regular methods. You should use `async for` to iterate the cursor too.
```
u = User(username="user")
u.email = 'user@email.com'
u.your_custom_method()
await u.save(db, session=session)
```
You can also consult with [CRUD docs](https://aiomongodel.readthedocs.io/en/latest/getting-started.html#crud): there are some examples for crud there.
